### ISSUE TITLE
DllNotFoundException in Unity upon play?

### ISSUE THREAD

**Issue by lehtiniemi** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#1]
### Issue Summary
I downloaded the project, ran GetModels and GetPlugins and downloaded them all. I then opened the proejct in Unity and hit play. I get the following error:
```
: openpose
OpenPose.OPWrapper.OPRegisterCallbacks () (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:29)
OpenPose.Example.OpenPoseUserScript.Start () (at Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs:69)

```

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
Hit play in Demo project in Unity

### Errors (if any)
: openpose
OpenPose.OPWrapper.OPRegisterCallbacks () (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:29)
OpenPose.Example.OpenPoseUserScript.Start () (at Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs:69)

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK
```
: openpose
OpenPose.OPWrapper.OPRegisterCallbacks () (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:29)
OpenPose.Example.OpenPoseUserScript.Start () (at Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs:69)
```

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
OpenPose Unity Plugin v1.0.0alpha-1.5.0

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?
Downloaded the unity plugin zip, unzipped it, ran get****.bat for both models and plugins and tried to run the Demo-project in Unity. Machine: Windows 10, Unity 2018.2.6f1

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):
-

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
-

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):
-

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:
-

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):
-

9. If **Windows** system:
    - Portable demo or compiled library?
Unity plugin. I tried separately to download the portable demo and it worked.

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).
-

**Comment by SoCohesive** [comment]
I am experiencing the same issue

**Comment by ZiuTinyat** [comment]
Did you install the [openpose prerequisites](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#prerequisites)? (e.g. CUDA and CUDNN if you are using Nvidia)

**Comment by TheBossBaby** [comment]
I am also facing the same issue.

**Comment by ZiuTinyat** [comment]
The issue is in the [faq](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/doc/faq.md) now and it will be closed until further following up.

**Comment by ghost** [comment]
I've got same issue.
But I while I run the source of openpose which I download from source code and run the 'OpenPoseDemo.exe' can run well, so I release the Unity plugin dll and replace the dll inside Unity project. But still bothering me ..
