### ISSUE TITLE
LOW fps Issue

### ISSUE THREAD

**Issue by hamzaraza06** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#13]
hi guys i am facing issue with FPS when ever i click on game window my fps drops to around 10fps and when i click on console window fps boost to 60fps. In other words when my game window is in focus fps drops to 10
![capture](https://user-images.githubusercontent.com/35335528/53735786-b8a92a00-3ea9-11e9-8a90-7ccb114532c9.PNG)
![capture1](https://user-images.githubusercontent.com/35335528/53735788-b941c080-3ea9-11e9-8094-eea5a6a7891d.PNG)

**Comment by ZiuTinyat** [comment]
Hi, I'm sorry for my late reply. 

This looks like a bug related to framerate calculation. I will fix it and update here!

**Comment by gineshidalgo99** [comment]
Fixed in the latest commit. Please, let us know if you still face this error.

**Comment by hamzaraza06** [comment]
Thanks @ZiuTinyat  and @gineshidalgo99 issue has been fixed. Now i have constant 12.5 fps is this due to camera or still their is some issue ? should i upgrade my camera?

**Comment by gineshidalgo99** [comment]
Then I should close the issue.

About low camera FPS, that's already opened in #2. We will update in there after it is fixed, we hope to fix that one within the next 1-2 weeks.

Best
