### ISSUE TITLE
Replace webcam w/ projector?

### ISSUE THREAD

**Issue by molecule** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#14]
Not an issue more of a question!

I'd really like to use a projector for this instead of a webcam. Basically the input would be a projector instead of a webcamera to make it easy to do some low-fi projection mapping using OpenPose. The projector would be connected over HDMI instead of USB. Looking at the code, it seems you have created a custom dll that supports webcams, is that right? **I'd be happy to write the code for this, if you think it's possible and can give me some idea of the overall architecture.**

Here's where the options are (includes webcam, flir camera, etc.):
https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/249b2e73f8bb1ffbf0a74708880c47492ff02681/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPEnums.cs#L65

And here's where the wrapper 'binds' them: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPWrapper.cs#L159

Here's the call in the binding:
https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPBind.cs#L79

**Comment by gineshidalgo99** [comment]
This is quite tricky, given that it actually means implementing that functionality with OpenPose, and then later update Unity plugin with the updated OpenPose version that supports that.

If you only need it on OpenPose, then I would recommend you to open this same issue as an issue in OpenPose repo itself, but what you should do it is to start from e.g.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/13_synchronous_custom_input.cpp

And replace the input code by your projector code. Then you would have OpenPose working for that projector.

However, if you really need to use Unity after that, then that code would have to actually be integrated inside OpenPose. I could do that once you have a working version based on example 13, but only if it is useful for the community. I.e., does that code work for 1 projector or for all of them? If it's only one, which brand? Does it require any special SDK to run it? etc...

**Comment by molecule** [comment]
Super helpful response, thank you! I'll look into this and let you know. Ideally it would support all projectors so I will see how possible this is, and create a new issue on the OpenPose repo if it makes sense.

**Comment by gineshidalgo99** [comment]
Please, feel free to open a new issue in OpenPose itself with a working demo if you have it, then we can see whether it can be easily be officially supported with OpenPose rather than just being a demo :)
