### ISSUE TITLE
OpenPose sprites not getting rendered inside Unity Editor in Windows10

### ISSUE THREAD

**Issue by RaymondDixon** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#17]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about OpenPose or 3rd party libraries**:
    - OpenPose-related issues should check the [official OpenPose GitHub repository](https://github.com/CMU-Perceptual-Computing-Lab/openpose).
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
While running Demo.scene the pose sprites are not getting rendered, instead getting a grey image in Unity Canvas. 

### Executed Command (if any)
Didnt execute any command. Downloaded the Plugins and models.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- **Help wanted**
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

Didnt get any Errors

2. **OpenPose version**: OpenPose Unity Plugin default? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.5.0)?

Default from OpenPose Unity Plugin

3. **General configuration**:
    - **Operating system** (`lsb_release -a` in Ubuntu):  Windows 10
    - **Release or Debug mode**? (by default: release):  Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...? VS2015 Enterprise Update 3

4. **Non-default settings**:
    - Any custom OpenPose configuration with respect to the default version? (by default: no): No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? Default
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?  OpenPose default (only Windows)

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):  release 9.0, V9.0.176
    - **cuDNN version**: 
    - **GPU model** (`nvidia-smi` in Ubuntu): Nvidia 1080

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Windows** system:
    - Default OpenPose DLL or Portable demo or compiled library? Default OpenPose DLL

9. If **speed performance** issue:
    - Run the OpenPose binaries and report the OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

After cloning the Repo, after downloading the models and Plugins. Using Unity 2018.1.6.f1(64bit) inside Editor While running the Demo.scene On Unity game view i get only grey image on the canvas and the skeleton sprites are not getting rendered. I am not getting any Errors in console. But when i checked the Gameobjects hierarchy i found it as below
```
OpenPose
OrthoCamera
Canvas
     BackgroundImage
     OpenPoseLogo
     FPS
     People
     HumanContainer
          Missing Prefab
          Missing Prefab
          Missing Prefab
          Missing Prefab
          Missing Prefab
    Control
EventSystem
```

I think the child of HumanContainer Game Object are missing some prefab. I followed and downloaded the Plugins and models and the entire repo multiple times under new Unity project. Still getting only Grey image in the Unity Editor Game view. But the actual OpenPose Release binaries are working with webcam and video input in my system. But OpenPose Unity plugin is not working. Please help how to proceed from current status.

**Comment by ZiuTinyat** [comment]
Missing prefab? I think it might be some linking error in Unity. 

Anyway try this: there should be five `Human2D_Body25` gameObjects under `HumanContainer`. The prefab can be found in `Assets\OpenPose\Examples\Prefabs`. Try replacing the missing prefabs with that.

**Comment by ZiuTinyat** [comment]
The issue is closed until further following up.
