### ISSUE TITLE
VideoCapture (IP camera/video) could not be opened for path: 'C:/video.avi'. If it is a video path, is the path correct?

### ISSUE THREAD

**Issue by itfantasyio** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#19]
I can make sure that the path is certainly right.
And the OpenPoseDemo.exe has launched the 'C:/video.avi' successfully.
But when the unity environment, it always show the error : 

OP_Error: 
Error:
VideoCapture (IP camera/video) could not be opened for path: 'C:/video.avi'. If it is a video path, is the path correct?

Coming from:
- C:\Users\tz1\Documents\openpose\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():38
- C:\Users\tz1\Documents\openpose\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():42
- C:\Users\tz1\Documents\openpose\src\openpose\producer\producer.cpp:op::createProducer():471
- C:\Users\tz1\Documents\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1127
- C:\Users\tz1\Documents\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
- C:\Users\tz1\Documents\openpose\src\openpose\unity\unityBinding.cpp:op::openpose_main():453
- [Error occurred in a destructor, so no std::exception has been thrown. Returning with exit status 0]

UnityEngine.Debug:LogError(Object)
OpenPose.OPWrapper:<OPLog>m__0(String, Int32) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:231)
OpenPose.OPBind:_OPRun()
OpenPose.OPWrapper:OPExecuteThread() (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:268)

How can I solve it? Please..

Thanks!

**Comment by ZiuTinyat** [comment]
Yep we noticed this error. 

We will make it work and update here.

**Comment by ZiuTinyat** [comment]
Hi, the new version should work with videos. Try it!

**Comment by gineshidalgo99** [comment]
Note: You will have to remove the plugins.zip and OpenPose DLLs and re-download the latest ones after you download the latest code!

Closing this then! (let us know if it does not work yet!)

**Comment by itfantasyio** [comment]
hey, i'm too late! thanks very much ~ ~

**Comment by Keneyr** [comment]
I used the latest code and resources , but still the same problem... seems the bug not fixed?

**Comment by Keneyr** [comment]
OP_Error: 
Error:
Folder -1\ does not exist.

Coming from:
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():312
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():366
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():408
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\producer\imageDirectoryReader.cpp:op::getImagePathsOnDirectory():22
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\producer\producer.cpp:op::createProducer():471
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1187
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\unity\unityBinding.cpp:op::openpose_main():453
- [Error occurred in a destructor or in the OpenPose Unity Plugin, so no std::exception has been thrown. Returning with exit status 0]

UnityEngine.Debug:LogError(Object)
OpenPose.<>c:<.cctor>b__29_0(String, Int32) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:233)
OpenPose.OPBind:_OPRun()
OpenPose.OPWrapper:OPExecuteThread() (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:270)
System.Threading.ThreadHelper:ThreadStart()

**Comment by Keneyr** [comment]
‘C:/video.avi’

 why not use relative paths.... but use an absolute path in unity?
