### ISSUE TITLE
How to work in UE4?

### ISSUE THREAD

**Issue by rebider** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#21]

**Comment by ZiuTinyat** [comment]
For this repository, it is only for Unity users. 

If you want to try openpose with UE4, my suggestion would be working on your modification of openpose library, creating interfaces to transmit data (some codes in unityBinding.cpp may help). 

I have no idea how UE4 works to support plugins but openpose side would be similar. 

Supporting UE4 is outside the scope of this repository, and may or may not be our consideration in the future.
