### ISSUE TITLE
How to keep track of the same person in time?

### ISSUE THREAD

**Issue by HideWorld** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#23]
### Issue Summary
I would like to  keep track of the same person in time。
### Type of Issue
- Help wanted

In the documentation, I see poseIds can keep track of the same person in time. 
But I use dataum.poseIds[bodyIndex] to get that everyone's return value is - 1. So, what's wrong with me?

Thanks

**Comment by gineshidalgo99** [comment]
OpenPose does not provide that functionality yet. There is on-going efforts to release that functionality, which is (for now) expected before the summer starts. This is not a question about the Unity plugin but rather about OP, so I will close it here. Check the OpenPose README to know when it is out. Thanks
