### ISSUE TITLE
Getting stuck at retrieving 2D pose keypoints 

### ISSUE THREAD

**Issue by KathySwe** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#24]
!!!actually not an issue more like question. Now I am getting stuck at retrieving 2D pose keypoints in Unity. Please help me. I would like to get the key points of pose( like x,y position in each frame) ? 
I really appreciate that if someone give hint to me how to get the key points of our body part.

**Comment by ZiuTinyat** [comment]
The keypoints info is stored in [OPDatum,poseKeypoints](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPDatum.cs#L44), which can be obtained from [OPWrapper.GetOutput()](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPWrapper.cs#L67) for every frame. An example can be found in [OpenPoseUserScript](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs#L161).

Hope this would help!

**Comment by KathySwe** [comment]
> The keypoints info is stored in [OPDatum,poseKeypoints](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPDatum.cs#L44), which can be obtained from [OPWrapper.GetOutput()](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPWrapper.cs#L67) for every frame. An example can be found in [OpenPoseUserScript](/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs#L161).
> 
> Hope this would help!

it gave help thank you very much @ZiuTinyat
