### ISSUE TITLE
Error 404 with pose files

### ISSUE THREAD

**Issue by ghost** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#30]
When attempting to use getModels.bat in order to get the pose files for the Unity plugin, they are retrieving error 404. It's not happening with the other models, only with pose models.

**Comment by gineshidalgo99** [comment]
Please, try again in a few minutes. It is usually a network issue (either from your side or from our server). Let us know if it does not work after several trials during different times.

**Comment by ghost** [comment]
Thanks! I managed to download the Windows pose models and then transfer them to the Unity Plugin. Right now, I'm trying to detect hand coordinates, so when they reach, for example, right side of the screen, a colision is detected. Is there any way I can get the hands coordinates like this?

**Comment by ZiuTinyat** [comment]
You can get the positions of hand in `datum.handKeypoints` in [OpenPoseUserScript](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Examples/Scripts/OpenPoseUserScript.cs#L161), when hand detecting is enabled. 

More info about the data structure can be found in [OPDatum](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPDatum.cs#L124)

The collision to the border is not detected inside openpose so you may need to write your own detector. 

A simple hint: position is close enough to the border and some fingers are not detected.

**Comment by ghost** [comment]
Thanks!
