### ISSUE TITLE
Any information about "public MultiArray<float> poseKeypoints3D" support? :)

### ISSUE THREAD

**Issue by steveod0701** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#33]
when is "3-D Reconstruction parameters" going to be supported? thanks :)
![3](https://user-images.githubusercontent.com/30585322/58773524-4a831900-85f8-11e9-9bbb-b807f97079f5.PNG)

**Comment by ZiuTinyat** [comment]
This parameter corresponds to the 3D reconstruction function in OpenPose, which is still in the experimental phase. So those parameters won't be officially supported until OpenPose releases this function. 

But if you are interested in using this experimental function in OpenPose, you need to modify OpenPose code in [unityBinding.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/unity/unityBinding.cpp#L131): add a function similar to sendPoseKeypoints which passes the 3D data to Unity datum. Then compile your OpenPose dll with Unity support flag on and put that into your Unity project folder.
