### ISSUE TITLE
Instant crash in unity 2018.3.3f1 on Windows 10 after latest commit (worked w/ prior commit).

### ISSUE THREAD

**Issue by molecule** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#4]
I downloaded this a few weeks ago (before the latest commit) and it worked great.
Now with the newest commit, unity crashes instantly. Please let me know how to report more information...the crash is instant so I get nothing from the console. 

The earlier version worked! I'm using the same version of unity on the same desktop Windows machine in both cases.

### Issue Summary
Instant crash when trying to run "demo" version after latest commit (21 hours ago).

### Executed Command (if any)
"Play" button on demo scene from Unity.

### OpenPose Output (if any)
None: unity crashes instantly.

### Errors (if any)
None: unity crashes instantly.

### Type of Issue
- Execution error
Unity crashes instantly.

### Your System Configuration
1. **Whole console output** There is no console output: Unity crashes instantly.

2. **OpenPose version**: Latest GitHub code crashes, code w/ prior commit works fine.

3. **General configuration**:
    - **Installation mode**: Unity plugin in both cases.
    - **Operating system** Windows 10, 64-bit in both cases 
    - **Release or Debug mode**? Not sure? Just running from unity.
    - Compiler n/a?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? No.
    - Any other custom CMake configuration with respect to the default version? No.

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** N/A?
    - **OpenCV version**: OpenPose default.

6. If **GPU mode** issue: It's the default so not sure if it's CPU or GPU? I'm just using the Unity Plugin. 
    - **CUDA version** : N/A?
    - **cuDNN version**: N/A?
    - **GPU model**: NVIDIA GeForce GTX 1070 but N/A?

7. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel Core i7-7700K CPU @ 4.20GHz (8 CPUs) ~4.2GHz
    - Total **RAM memory** available: 32768MB RAM

9. If **Windows** system:
    - Portable demo or compiled library? Portable Demo, unity plugin.

**Comment by gineshidalgo99** [comment]
We forgot to update with the new OpenPose DLLs. We will fix it very soon (today/tomorrow) and update the repo and update you! Sorry!

**Comment by molecule** [comment]
Thanks!! Great work by the way - excellent documentation, demo video, and of course the whole tool is very cool!!! Will be playing with it a lot over the next few weeks.

**Comment by gineshidalgo99** [comment]
Hi @molecule , fixed in the latest update! Please, re-download the latest code. And following the (updated) doc/faq.md or doc/installation.md, remove the current OpenPose DLLs and re-download the latest ones that come with the updated version. Let me know if something is not clear in the doc or still failing!

**Comment by FrenchDoge** [comment]
Hi molecule and gineshidalgo99

I have a very similar issue (it doesn't crash instantly but few seconds after clicking play button), but with the most recent versions installed.

I could capture the console of unity before it crashes : (i hope the link works)
https://ibb.co/2hRm69v



### Your System Configuration
1. **Whole console output** There is no console output: Unity crashes instantly.

2. **OpenPose version**: OpenPose Unity Plugin default

3. **General configuration**: 
    - **Operating system** : Windows 10, 64-bit
    - **Release or Debug mode** : release
    - Compiler : VS 2017 community

4. **Non-default settings**:
    - Any custom OpenPose configuration with respect to the default version? : no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue: I'm using the CPU_ONLY option, but just in case :
    - **CUDA version** : 10 
    - **cuDNN version**: 7.5
    - **GPU model** : Nvidia Geforce GTX 760

7. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel Core i7-4700K CPU @ 3.4GHz  3.4GHz
    - Total **RAM memory** available: 16GB

8. If **Windows** system:
    - Default OpenPose DLL or Portable demo or compiled library? Not demo, Last version of Openpose installed directly downloaded at the root of the github. Installed following the installation guide

**Comment by ZiuTinyat** [comment]
Hi FrenchDoge, 

We provided checking walkthrough here in [faq](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/doc/faq.md#unity-crashes).
