### ISSUE TITLE
Error 404 when downloading pose files

### ISSUE THREAD

**Issue by cwule** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#40]
This question has already been asked in the closed issues section, but since the answer "Wait for several minutes and try again" hasn't worked for me (trying for ~2h now) I am opening it again.

When running getModels.bat, the face and hand are properly downloaded but I get the following error for the pose:
`Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-04 13:50:12 ERROR 404: Not Found.`

Update: One day later the 404 error still persists.

**Comment by Vilyx** [comment]
I found solution, just replace 
set BODY_25_FOLDER=%POSE_FOLDER%body_25\\
with
set BODY_25_FOLDER=%POSE_FOLDER%body_25/


SET COCO_FOLDER=%POSE_FOLDER%coco\\
with
SET COCO_FOLDER=%POSE_FOLDER%coco/

and 
SET MPI_FOLDER=%POSE_FOLDER%mpi\\
with 
SET MPI_FOLDER=%POSE_FOLDER%mpi/

at least it solved problem for me.

**Comment by ZiuTinyat** [comment]
The code is updated now!

**Comment by sid0407** [comment]
I am still getting the same error while running  a_downloadAndUpzipLmdbs.sh !
```
Proxy request sent, awaiting response... 404 Not Found
2020-12-03 13:01:59 ERROR 404: Not Found.
```

**Comment by Ankita18Mandal** [comment]
> I am still getting the same error while running a_downloadAndUpzipLmdbs.sh !
> 
> ```
> Proxy request sent, awaiting response... 404 Not Found
> 2020-12-03 13:01:59 ERROR 404: Not Found.
> ```

Hello @sid0407 
You could probably try option b,i.e, Generate the LMDB files by yourself as mentioned https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/tree/master/training
 ``` bash a_lmdbGetBody.sh```
It worked in my case ✌

**Comment by sid0407** [comment]
> > I am still getting the same error while running a_downloadAndUpzipLmdbs.sh !
> > ```
> > Proxy request sent, awaiting response... 404 Not Found
> > 2020-12-03 13:01:59 ERROR 404: Not Found.
> > ```
> 
> Hello @sid0407
> You could probably try option b,i.e, Generate the LMDB files by yourself as mentioned https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/tree/master/training
> ` bash a_lmdbGetBody.sh`
> It worked in my case ✌

Hello @Ankita18Mandal 
Using the method b) is working for me. Thank you! 😊
