### ISSUE TITLE
Track only Hand keypoints

### ISSUE THREAD

**Issue by pkr97** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#49]
Thanks guys for making this possible. The hand key-point tracking is very robust.

I'm able to run this openpose plugin demo program in Unity 2019.

It crashes when I try to enable both face and hand tracking alongside body tracking. What could be the reason?

Combinations Working:
1. Only Body tracking
2. Body Tracking + hand key-point tracking
3. Body tracking + face landmark detection

Combinations that crash the Unity:
Body Tracking + Hand Key-point + facial landmark detection.
Note: the resolution is set to 
-1, 80
320, 320
320, 320

What could be the reason for Unity crash?

Apart from the above mentioned issue I would like to know about another aspect.
Is it possible to track only hands using the caffeModel provided for hands?

I shall be waiting for some valuable inputs.

Thanks..

**Comment by ZiuTinyat** [comment]
Hi, I think it crashes mainly because your GPU's memory is not enough for all together. Try decreasing the resolution to 80 for hand and face. 

Tracking only hands: no it couldn't. Tracking hands requires the result of arms from body tracking.
