### ISSUE TITLE
Unity Help on the pose model selection

### ISSUE THREAD

**Issue by pavchavan** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#5]
In openpose unity plugin , the pose model body_25 is selected ?
and where is the "pose_deploy.prototxt" and "pose_iter_584000.caffemodel" files are present.

and from where OpenPose is accessing the files for the Body_25 in unity project ?

can you let me know how its running?
and how is the flow?

**Comment by ZiuTinyat** [comment]
By default, OpenPose uses model `body_25`. 

The model files are stored in `openpose_unity_plugin\OpenPosePlugin\Assets\StreamingAssets\models\pose`, if you have already run `getModels.bat` to download them. 

Unity passes the path of the model folder to OpenPose as a parameter, and OpenPose will find the file by itself. 
The model folder can be set in `OPConfigurePose()` in [OPWrapper](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/OpenPosePlugin/Assets/OpenPose/Modules/Scripts/OPWrapper.cs#L86) and by default, it points to the streaming assets folder. 

Does this help?

**Comment by pavchavan** [comment]
Thank you,
the reply is really helpful to under stand the Model Selection.
