### ISSUE TITLE
Binary runs and Unity crashes. Camera frame empty ERROR

### ISSUE THREAD

**Issue by kemoon** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#51]
I work on Win10 machine,  graphics GTX1080.
The testBinary.bat works in vide mode by setting --net_resolution -1312x736

I set the same values of net_resolution on Unity project and run it (in video mode).

The demo starts without showing anything and I read the following:
OP_Log: Starting OpenPose...

than I can only stop the demo. Unity doesn't crash.

![image](https://user-images.githubusercontent.com/7473940/64857892-2509a080-d626-11e9-9949-a314a308828d.png)

If I run the Unity demo in webcam mode I get the same but I read the following log:

OP_Log: Camera frame empty (it has occurred for the last N consecutive frames).

Afterwards, if I stop the demo, Unity freezees.

Any hints?

Thanks!

![image](https://user-images.githubusercontent.com/7473940/64857306-72850e00-d624-11e9-8fde-39afd507abc4.png)

**Comment by kemoon** [comment]
I managed to successfully run the video mode on Unity by setting the path to video in "Producer string" and enabling the video mode.

I am still not able to run it in webcam mode neither with the Logitech cam nor with the RGB camera of the Intel Realsense D415. I have a desktop PC without integrated webcam

**Comment by jreisam** [comment]
Had the same issue, solved changing my Unity 2019 version, to **2018.4.17f1** (2018 versions are fully compatible with OpenPose - check **Software Versions** section in https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/doc/installation.md )

**Comment by jreisam** [comment]
> I work on Win10 machine, graphics GTX1080.
> The testBinary.bat works in vide mode by setting --net_resolution -1312x736
> 
> I set the same values of net_resolution on Unity project and run it (in video mode).
> 
> The demo starts without showing anything and I read the following:
> OP_Log: Starting OpenPose...
> 
> than I can only stop the demo. Unity doesn't crash.
> 
> ![image](https://user-images.githubusercontent.com/7473940/64857892-2509a080-d626-11e9-9949-a314a308828d.png)
> 
> If I run the Unity demo in webcam mode I get the same but I read the following log:
> 
> OP_Log: Camera frame empty (it has occurred for the last N consecutive frames).
> 
> Afterwards, if I stop the demo, Unity freezees.
> 
> Any hints?
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/7473940/64857306-72850e00-d624-11e9-8fde-39afd507abc4.png)

Had the same issue, solved changing my Unity 2019 version, to **2018.4.17f1** (2018 versions are fully compatible with OpenPose - check **Software Versions** section in https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/doc/installation.md )

**Comment by jreisam** [comment]
Note the exacly version 2018.4.17f1 , using others 2018.xx.x.x versions was resulting in random freezing / crashing Unity.
