### ISSUE TITLE
I can't see hand keypoints, please help me!

### ISSUE THREAD

**Issue by electronicYH** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#52]
I can run testBinary.bat well.
But, when I use Demo.unity with my video, I can't see the hand keypoints, however, I can see the face keypoints.
Please help me.

**Comment by ZiuTinyat** [comment]
You need to enable hand detection, and hand detection also requires the detection of arms. So you need to show your arms in camera to detect the hands.
