### ISSUE TITLE
Can not get models- getModels.bat can not resolve the URL

### ISSUE THREAD

**Issue by MahmoudAshraf-CIS** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#68]
### Issue Summary
Can not get models- getModels.bat can not resolve the URL

### Executed Command (if any)
Running the **getModels.bat** as mentioned in the [installation guide](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin/blob/master/doc/installation.md)

### getModels.bat Output

> ------------------------- BODY, FOOT, FACE, AND HAND MODELS -------------------------
----- Downloading body pose (COCO and MPI), face and hand models -----
------------------------- POSE (BODY+FOOT) MODELS -------------------------
Body (BODY_25)
--2020-08-24 00:29:56--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Unknown error.
Retrying.

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** https://pastebin.com/MukJBvUc

2. **OpenPose version**:  OpenPose Unity Plugin v1.0.0alpha-1.5.0

3. **General configuration**:
    - **Operating system** Windows 10
    - **Release or Debug mode** release 

Am assuming the host http://posefs1.perception.cs.cmu.edu/OpenPose/models/ is down 
I tried to change my DNS configuration and using VPN but always failed to resolve the URL even on the browser 

is there any alternative to getModel.bat to get the models i see it's trying to download `caffemodel` files and these files are ignores in the repo .gitignore

**Comment by gineshidalgo99** [comment]
See See https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
