### ISSUE TITLE
Unresolved the path

### ISSUE THREAD

**Issue by aeliusventure** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#8]
### Type of Issue
Issue of the path.

 **Windows** system:
  OP_Error: - C:\Users\tz1\Documents\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
UnityEngine.Debug:LogError(Object)
OpenPose.OPWrapper:<OPLog>m__0(String, Int32) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:227)
OpenPose.OPBind:_OPRun()
OpenPose.OPWrapper:OPExecuteThread() (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:261)

**Comment by ZiuTinyat** [comment]
Hi, this most probably seems to be an error with your CUDA installation.

Can you run the OpenPose binary demo as the documentation suggests?

**Comment by potkpot** [comment]
> Hi, this most probably seems to be an error with your CUDA installation.
> 
> Can you run the OpenPose binary demo as the documentation suggests?

So it looks like it have absolute paths inside dll's. It works with webcam and have same errors in any other input types
![pathtz1](https://user-images.githubusercontent.com/6442727/52856235-ee71b300-3134-11e9-9419-90ff27a668a0.png)

**Comment by gineshidalgo99** [comment]
The absolute paths mean nothing, you can ignore them, they are just from the computer where it was compiler, but they just help showing where it is coming from inside OpenPose. As the error clearly says, "No camera found", you do not have a webcam available. So this is not a Unity plugin issue, but rather your PC or OpenPose itself.

Again, did you run default binary OpenPose?
