### ISSUE TITLE
Test binary not working

### ISSUE THREAD

**Issue by StephanBis** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#85]
After running _getPlugins.bat_ and _getModels.bat_, we cannot get _testBinary.bat_ working on our higher spec PC. The binary seems to run fine and starts up the window, but it stays black and stops responding. 

Specs:
- Windows 11
- Nvidia 3080ti
- Trust USB webcam

Latest CUDA is installed.

![image](https://user-images.githubusercontent.com/10954823/183462870-dbbbff48-483b-411e-a07a-2bf11d25e475.png)

**Comment by junghyonil123** [comment]
how fix it??

**Comment by StephanBis** [comment]
> how fix it??

We didn't fix it as 30+ series GPU's aren't supported.
